# -*- coding: utf-8 -*-
"""Les vingt scripts des vidéos. Un script = une liste de groupes de mots.

Chaque groupe est ce qui s'affiche à l'écran en même temps, au moment où la voix
le prononce. On l'écrit AVEC sa ponctuation — c'est ce que la voix lit — et le
générateur l'affiche sans, en capitales, comme dans les originaux.

Trois marques, à l'intérieur d'un groupe :
    *mot*    le mot ressort en jaune
    !mot!    en rouge
    +mot+    en vert
    /        ce qui précède est la ligne large, ce qui suit la ligne étroite

« noir » : combien de groupes, au début, passent sur fond noir avant le premier
tableau — c'est l'accroche.

Chaque script part d'un article du guide (« article »), qui est la matière du
texte et le lien de la légende. Le penseur cité l'est pour une idée qu'il a
réellement écrite, paraphrasée — jamais une citation inventée.

Ce que les scripts ne disent JAMAIS : que le test est gratuit (il ne l'est pas),
un prix, ou quoi que ce soit qui ressemble à un diagnostic.
"""

CTA = [
    "Seize situations du quotidien, / quatorze émotions,",
    "et la place / qu'elles occupent chez toi.",
    "Fais le test. / Le lien est en *bio*.",
]

SCRIPTS = [
  {
    "id": "01-ca-va", "titre": 'Répondre que ça va', "images": ['adult woman forced smile office', 'man hiding sadness behind smile', 'person alone window rain thinking', 'coffee cup morning alone table', 'tired adult face close up', 'everything is fine note'], "article": "repondre-que-ca-va", "penseur": "Darwin",
    "musique": "Dark-Times.mp3", "noir": 3,
    "groupes": [
      "Tu réponds *ça va* / dix fois par jour.",
      "Et tu sais très bien / que c'est !faux!.",
      "Ton visage, lui, / ne ment pas.",
      "Il y a cent cinquante ans, / Darwin l'a observé :",
      "l'émotion s'écrit / sur le visage",
      "+avant+ / qu'on décide de la montrer.",
      "Les sourcils. / La mâchoire. / Le souffle.",
      "Ils parlent / une seconde avant toi.",
      "Traduis-le / simplement.",
      "Ce que tu ne dis pas / se voit quand même.",
      "Alors compte, / cette semaine,",
      "combien de fois / tu as dit *ça va*",
      "alors que / non.",
      "Si c'est plus de trois,",
      "ce n'est pas / de la politesse.",
      "C'est une émotion / qui n'a plus de mot.",
      "Et une émotion sans mot / ne disparaît pas.",
      "Elle *attend*.",
    ] + CTA,
    "legende": "Tu dis « ça va » et ton visage dit autre chose. Darwin l'avait vu avant tout le monde.",
  },
  {
    "id": "02-colere", "titre": 'La colère', "images": ['angry man', 'clenched fist', 'slammed door', 'shouting argument', 'storm clouds dark', 'broken glass'], "article": "colere", "penseur": "Sénèque",
    "musique": "Anguish.mp3", "noir": 3,
    "groupes": [
      "Tu as claqué / une porte.",
      "Et une heure après, / tu ne comprends plus / !pourquoi!.",
      "C'est normal. / Et c'est ancien.",
      "Il y a deux mille ans, / Sénèque rapportait",
      "que les sages appelaient la colère / une *courte folie*.",
      "Pas une faiblesse. / Pas un défaut.",
      "Une tempête / qui passe,",
      "et qu'on peut apprendre / à regarder venir.",
      "Traduis-le / simplement.",
      "La colère a toujours / un +signal+ avant.",
      "La mâchoire qui se serre. / Le ton qui monte d'un cran.",
      "La phrase qu'on prépare / au lieu d'écouter.",
      "Ce signal, / tu l'as.",
      "La question, / c'est de savoir",
      "si tu le vois / *avant* la porte",
      "ou / !après!.",
      "Ce n'est pas une question / de caractère.",
      "C'est une question / d'entraînement.",
    ] + CTA,
    "legende": "La colère est une courte folie, disaient les anciens. Elle a un signal, et il arrive avant la porte qui claque.",
  },
  {
    "id": "03-ruminer", "titre": 'Ruminer une critique', "images": ['office meeting stress', 'man thinking window night', 'overthinking', 'lying awake ceiling', 'notebook writing pen', 'empty conference room'], "article": "ruminer-une-critique-au-travail", "penseur": "Marc Aurèle",
    "musique": "Long-Note-Two.mp3", "noir": 3,
    "groupes": [
      "Une phrase / en réunion.",
      "Cinq secondes / pour la dire.",
      "!Trois jours! / pour la ruminer.",
      "Il y a dix-huit siècles, / un empereur écrivait, / pour lui seul :",
      "si une chose extérieure te fait souffrir,",
      "ce n'est pas la chose / qui te trouble,",
      "c'est le *jugement* / que tu portes sur elle.",
      "Il s'appelait / Marc Aurèle.",
      "Traduis-le / simplement.",
      "La critique a duré / cinq secondes.",
      "Le reste, / c'est toi qui l'ajoutes.",
      "Alors fais / une chose :",
      "sépare ce qui a été +dit+",
      "de ce que tu as / *entendu*.",
      "Écris les deux.",
      "Souvent, / ce n'est pas la même phrase.",
      "Et c'est la deuxième / qui te tient éveillé.",
    ] + CTA,
    "legende": "Cinq secondes pour la dire, trois jours pour la ruminer. Marc Aurèle avait un mot pour ça.",
  },
  {
    "id": "04-dimanche-soir", "titre": 'Le dimanche soir', "images": ['sunday evening sofa', 'dusk apartment window', 'alarm clock bedroom', 'rain window evening', 'laptop dark room', 'empty street evening'], "article": "angoisse-dimanche-soir", "penseur": "Alain",
    "musique": "Colorless-Aura.mp3", "noir": 3,
    "groupes": [
      "Dimanche, / dix-huit heures.",
      "Rien ne s'est passé. / Et pourtant, / quelque chose !descend!.",
      "Tu connais / cette heure-là.",
      "Il y a un siècle, / un professeur de lycée",
      "écrivait chaque jour / un texte court sur le bonheur.",
      "Il s'appelait / Alain.",
      "Et il disait ceci :",
      "le pessimisme / est d'*humeur*,",
      "l'optimisme / est de +volonté+.",
      "Traduis-le / simplement.",
      "Ce qui descend le dimanche soir / n'est pas une idée.",
      "C'est une humeur. / Elle vient toute seule.",
      "Ce qui ne vient pas tout seul, / c'est ce que tu en fais.",
      "Alors regarde, / dimanche prochain :",
      "est-ce que tu redoutes / la semaine,",
      "ou est-ce que tu redoutes / *une* chose",
      "que tu n'as pas / encore nommée ?",
      "Ce n'est jamais / toute la semaine.",
    ] + CTA,
    "legende": "Dimanche, 18 h, et quelque chose descend. Ce n'est jamais toute la semaine — c'est une chose, pas encore nommée.",
  },
  {
    "id": "05-jalousie-couple", "titre": 'La jalousie dans le couple', "images": ['couple distance', 'checking phone secretly', 'woman looking at phone jealous', 'couple back to back', 'unanswered phone', 'shadow two people'], "article": "jalousie-dans-le-couple", "penseur": "La Rochefoucauld",
    "musique": "Cold-Sober.mp3", "noir": 3,
    "groupes": [
      "Un prénom / dans une conversation.",
      "Et tout à coup, / tu +surveilles+.",
      "Tu détestes ça. / Tu le fais quand même.",
      "Il y a quatre siècles, / un moraliste français",
      "écrivait que la jalousie / se nourrit / dans les *doutes*,",
      "et qu'elle finit / sitôt qu'on passe",
      "du doute / à la certitude.",
      "Il s'appelait / La Rochefoucauld.",
      "Traduis-le / simplement.",
      "La jalousie ne vit pas / de ce que tu sais.",
      "Elle vit de ce que / tu ne sais !pas!.",
      "Alors pose-toi / la vraie question :",
      "de quoi / as-tu peur ?",
      "Pas de qui. / De *quoi*.",
      "D'être remplacé ? / De ne pas suffire ?",
      "De l'avoir déjà / senti une fois ?",
      "Ce n'est pas l'autre / qui te répondra.",
      "C'est toi.",
    ] + CTA,
    "legende": "La jalousie se nourrit dans les doutes, écrivait La Rochefoucauld. La question n'est pas « qui ». C'est « de quoi ».",
  },
  {
    "id": "06-message-vu", "titre": 'Message vu, sans réponse', "images": ['phone screen waiting', 'typing message', 'person waiting phone', 'notification smartphone', 'empty chat', 'night phone light face'], "article": "message-vu-sans-reponse", "penseur": "Sénèque",
    "musique": "Heart-of-Nowhere.mp3", "noir": 3,
    "groupes": [
      "*Vu*. / Il y a deux heures.",
      "Et toujours / rien.",
      "Ton cerveau a déjà / écrit trois scénarios.",
      "Il y a deux mille ans, / Sénèque écrivait à un ami :",
      "nous souffrons plus souvent / en *imagination*",
      "qu'en +réalité+.",
      "Traduis-le / simplement.",
      "Le message n'a rien dit. / Le silence non plus.",
      "Les trois scénarios, / c'est toi.",
      "Alors fais / l'expérience :",
      "écris ce que tu crois / que ce silence veut dire.",
      "Puis écris / ce que tu !sais!.",
      "Compare / les deux colonnes.",
      "La première est pleine. / La seconde est vide.",
      "Ce n'est pas un signe. / C'est une attente.",
      "Et une attente, / ça se regarde",
      "sans lui donner / une histoire.",
    ] + CTA,
    "legende": "« Vu », il y a deux heures. Sénèque l'écrivait déjà : on souffre plus souvent en imagination qu'en réalité.",
  },
  {
    "id": "07-parler-en-reunion", "titre": 'Parler en réunion', "images": ['meeting room raising hand', 'nervous presentation', 'conference table people', 'public speaking anxiety', 'microphone empty room', 'hands sweating'], "article": "peur-de-parler-en-reunion", "penseur": "Montaigne",
    "musique": "Shadowlands-1---Horizon.mp3", "noir": 3,
    "groupes": [
      "Tu avais / la bonne idée.",
      "Tu l'as gardée / pour toi.",
      "Quelqu'un l'a dite / dix minutes après.",
      "Il y a quatre siècles, / Montaigne l'écrivait déjà :",
      "ce dont il avait / le plus peur,",
      "c'était / la *peur*.",
      "Pas la chose. / La peur de la chose.",
      "Traduis-le / simplement.",
      "Ce n'est pas la réunion / qui te bloque.",
      "C'est ce que tu imagines / +avant+.",
      "Le silence après ta phrase. / Un regard. / Un sourire de travers.",
      "Aucun des trois / n'est arrivé.",
      "Alors regarde / la prochaine fois :",
      "est-ce que ta gorge se serre / quand tu parles,",
      "ou !avant! / de parler ?",
      "Si c'est avant,",
      "ce n'est pas / un manque de courage.",
      "C'est une peur / qui a pris de l'avance.",
    ] + CTA,
    "legende": "Ce dont j'ai le plus peur, c'est la peur, écrivait Montaigne. En réunion, elle arrive avant la phrase.",
  },
  {
    "id": "08-surprise", "titre": 'La surprise', "images": ['surprised face', 'unexpected gift', 'opened door light', 'wide eyes', 'sudden rain umbrella', 'jack in the box'], "article": "surprise", "penseur": "Descartes",
    "musique": "Dreams-Become-Real.mp3", "noir": 3,
    "groupes": [
      "Une seconde. / Pas plus.",
      "L'émotion / la plus *courte* / de toutes.",
      "Et personne / n'y fait attention.",
      "Il y a quatre siècles, / Descartes classait les passions.",
      "Et il en mettait une / +avant+ toutes les autres.",
      "Pas la joie. / Pas la peur.",
      "L'*admiration* : / ce qu'on appelle / aujourd'hui / la surprise.",
      "Traduis-le / simplement.",
      "La surprise, / c'est la porte.",
      "Ce qui entre après, / c'est joie, / colère / ou peur.",
      "Mais la porte, / c'est elle.",
      "Alors observe, / la prochaine fois",
      "que quelque chose / t'arrive :",
      "qu'est-ce qui suit / la seconde de surprise ?",
      "Toujours / la même émotion ?",
      "Ou une différente / à chaque fois ?",
      "Ça en dit long / sur ce que tu !attends! / du monde.",
    ] + CTA,
    "legende": "Descartes plaçait la surprise avant toutes les autres passions. C'est la porte — regarde ce qui entre après.",
  },
  {
    "id": "09-pleurer", "titre": 'Pleurer pour un rien', "images": ['tears face', 'crying woman window', 'tissue box', 'rain on glass', 'hand wiping tears', 'emotional listening music headphones'], "article": "pleurer-pour-un-rien", "penseur": "William James",
    "musique": "Ossuary-5---Rest.mp3", "noir": 3,
    "groupes": [
      "Une pub. / Une chanson. / Un mot gentil.",
      "Et les larmes / montent.",
      "Pour *rien*, / tu dis.",
      "Il y a cent quarante ans, / un psychologue américain",
      "a retourné / la question.",
      "On croit qu'on pleure / parce qu'on est triste.",
      "William James disait : / on est triste",
      "parce qu'on / +pleure+.",
      "Le corps / d'abord.",
      "Traduis-le / simplement.",
      "Les larmes ne viennent pas / de la pub.",
      "Elles viennent d'un corps / qui était !plein!",
      "et qui a trouvé / une sortie.",
      "Alors quand ça monte / pour rien,",
      "ne cherche pas / ce qui vient d'arriver.",
      "Cherche ce qui / s'accumule / depuis des jours.",
      "Le rien, / c'est juste / la goutte.",
    ] + CTA,
    "legende": "On ne pleure pas parce qu'on est triste — on est triste parce qu'on pleure, disait William James. Le corps d'abord.",
  },
  {
    "id": "10-trois-heures", "titre": 'Trois heures du matin', "images": ['insomnia', 'bedroom night dark', 'alarm clock 3am', 'ceiling lying awake', 'moonlight bedroom', 'sleepless night'], "article": "se-reveiller-a-3h-du-matin", "penseur": "Kierkegaard",
    "musique": "Long-Note-One.mp3", "noir": 3,
    "groupes": [
      "Trois heures / du matin.",
      "Les yeux ouverts. / Et une pensée qui !tourne!.",
      "La même / que la nuit dernière.",
      "Il y a deux siècles, / un philosophe danois",
      "appelait l'angoisse / le *vertige* / de la liberté.",
      "Il s'appelait / Kierkegaard.",
      "Traduis-le / simplement.",
      "À trois heures du matin, / tu n'as rien à faire.",
      "Aucune tâche. / Aucun rendez-vous.",
      "Rien / pour tenir la pensée.",
      "Alors elle regarde / le vide,",
      "et le vide / lui donne le vertige.",
      "Ce n'est pas / le problème qui te réveille.",
      "C'est l'+espace+ / qu'il trouve à cette heure-là.",
      "Alors note-le. / Vraiment. / Sur un papier.",
      "Pas pour le résoudre.",
      "Pour lui donner / un endroit où être",
      "qui ne soit pas / ta tête.",
    ] + CTA,
    "legende": "Trois heures du matin, et la même pensée. Kierkegaard appelait ça le vertige de la liberté.",
  },
  {
    "id": "11-imposteur", "titre": "Le syndrome de l'imposteur", "images": ['applause office', 'self doubt mirror', 'award ceremony', 'nervous at desk', 'imposter mask', 'person hiding behind laptop'], "article": "syndrome-imposteur", "penseur": "Épictète",
    "musique": "Echoes-of-Time-v2.mp3", "noir": 3,
    "groupes": [
      "On te félicite.",
      "Et une voix, dedans, / dit : / *ils vont voir*.",
      "Ils vont voir / que tu ne mérites pas.",
      "Il y a deux mille ans, / un ancien esclave / devenu philosophe",
      "enseignait une seule chose : / distinguer",
      "ce qui +dépend+ de toi / de ce qui !n'en dépend pas!.",
      "Il s'appelait / Épictète.",
      "Traduis-le / simplement.",
      "Ton travail / dépend de toi.",
      "Leur verdict / ne dépend pas de toi.",
      "La voix qui dit / *ils vont voir*",
      "passe sa vie / dans la deuxième colonne.",
      "Alors fais / l'inventaire :",
      "ce que tu as fait, / vraiment, / cette semaine.",
      "Pas ce qu'ils / en penseront.",
      "Ce que tu as / fait.",
      "La liste est plus longue / que la voix.",
      "Elle l'est / toujours.",
    ] + CTA,
    "legende": "« Ils vont voir. » Épictète répondait déjà : sépare ce qui dépend de toi de ce qui n'en dépend pas.",
  },
  {
    "id": "12-dire-non", "titre": 'Dire non', "images": ['stop hand gesture', 'overworked desk papers', 'tired employee office', 'calendar full schedule', 'closed door', 'person overwhelmed laptop'], "article": "culpabilite-de-dire-non", "penseur": "Aristote",
    "musique": "Lost-Frontier.mp3", "noir": 3,
    "groupes": [
      "Tu as dit / *oui*.",
      "Tu voulais / dire non.",
      "Et maintenant / tu t'en veux / d'avoir dit oui.",
      "Il y a deux mille quatre cents ans, / Aristote écrivait",
      "qu'une émotion est juste / quand elle vise",
      "la bonne personne, / au bon +moment+, / pour la bonne raison.",
      "Traduis-le / simplement.",
      "Dire non n'est pas / une faute.",
      "C'est une émotion / qui a trouvé / sa bonne adresse.",
      "Ce qui te fait mal, / ce n'est pas le non.",
      "C'est l'idée que l'autre / va !moins t'aimer!.",
      "Alors vérifie :",
      "la dernière fois / que quelqu'un t'a dit non,",
      "tu l'as aimé / moins ?",
      "Ou tu as juste / réorganisé ta journée ?",
      "C'est ce qu'il fera / aussi.",
    ] + CTA,
    "legende": "Tu as dit oui, tu voulais dire non. Aristote : une émotion est juste quand elle vise la bonne personne, au bon moment.",
  },
  {
    "id": "13-amitie", "titre": "L'amitié qui s'éloigne", "images": ['two friends laughing old photo', 'empty chairs cafe', 'walking away friends', 'phone contacts scrolling', 'distance road', 'friends silhouette sunset'], "article": "amitie-qui-seloigne", "penseur": "Aristote",
    "musique": "Colorless-Aura.mp3", "noir": 3,
    "groupes": [
      "Vous étiez / inséparables.",
      "Et maintenant, / un message / tous les trois mois.",
      "Personne n'a rien fait. / Ça s'est juste !éloigné!.",
      "Il y a deux mille quatre cents ans, / Aristote distinguait",
      "trois amitiés : / celle de l'*utilité*,",
      "celle du *plaisir*, / et celle / de ce qu'on est.",
      "Les deux premières finissent / quand la raison finit.",
      "La troisième, / non.",
      "Traduis-le / simplement.",
      "Si l'amitié s'éloigne / quand le contexte change,",
      "c'était l'amitié / du contexte.",
      "Ce n'est pas / une trahison.",
      "C'est / sa nature.",
      "Alors demande-toi / ce qui te manque :",
      "la +personne+, / ou l'époque",
      "où vous étiez / ensemble ?",
      "La réponse change / ce que tu dois faire.",
    ] + CTA,
    "legende": "Inséparables, puis un message tous les trois mois. Aristote distinguait trois amitiés — et une seule survit au changement.",
  },
  {
    "id": "14-rupture", "titre": 'Après la rupture', "images": ['breakup alone', 'empty side of bed', 'photo torn', 'rain window sad', 'crystal salt', 'person walking alone city'], "article": "apres-la-rupture", "penseur": "Stendhal",
    "musique": "Anguish.mp3", "noir": 3,
    "groupes": [
      "C'est fini / depuis deux mois.",
      "Et tu penses encore / à cette personne",
      "comme si elle était / *parfaite*.",
      "Il y a deux siècles, / Stendhal a décrit",
      "ce que fait l'amour / à ce qu'on regarde :",
      "il le couvre / de +cristaux+.",
      "Une branche jetée / dans une mine de sel",
      "ressort couverte / de diamants.",
      "Il appelait ça / la cristallisation.",
      "Traduis-le / simplement.",
      "La personne qui te manque / n'existe pas.",
      "Elle est couverte / de cristaux.",
      "Et les cristaux, / c'est toi qui les as posés.",
      "Alors fais / l'exercice :",
      "écris trois choses / qui t'agaçaient / vraiment.",
      "Si tu n'en trouves / !aucune!,",
      "ce n'est pas / que c'était parfait.",
      "C'est que / tu regardes encore / la branche.",
    ] + CTA,
    "legende": "Deux mois après, cette personne te semble parfaite. Stendhal avait un mot pour ça : la cristallisation.",
  },
  {
    "id": "15-reconnaissance", "titre": 'Le manque de reconnaissance', "images": ['office late night working', 'applause colleagues', 'unnoticed worker', 'empty office desk', 'handshake boss', 'coffee cup desk night'], "article": "manque-de-reconnaissance-travail", "penseur": "Épicure",
    "musique": "Cold-Sober.mp3", "noir": 3,
    "groupes": [
      "Tu as tenu / le projet.",
      "Quelqu'un d'autre / a eu le *merci*.",
      "Et tu te dis / que ça ne te touche pas.",
      "Il y a deux mille trois cents ans, / Épicure séparait",
      "les désirs / +naturels+",
      "des désirs / !vains! :",
      "ceux qu'aucune quantité / ne remplit jamais.",
      "Traduis-le / simplement.",
      "Le besoin d'être vu / est naturel.",
      "Le besoin que ce soit / *lui* qui te voie,",
      "à ce moment-là, / devant tout le monde,",
      "c'est le désir / qui ne se remplit pas.",
      "Alors pose-toi / la question :",
      "qui, cette semaine, / a vu ce que tu as fait ?",
      "Pas celui / que tu attendais.",
      "N'importe qui.",
      "Il y a presque toujours / quelqu'un.",
      "Et tu ne le comptes / pas.",
    ] + CTA,
    "legende": "Tu as tenu le projet, un autre a eu le merci. Épicure séparait les désirs naturels de ceux qu'aucune quantité ne remplit.",
  },
  {
    "id": "16-fatigue", "titre": 'Toujours fatigué', "images": ['tired woman morning bed', 'exhausted man desk', 'rubbing eyes tired', 'endless scrolling phone bed', 'crowded street rush hour', 'person alone quiet room'], "article": "toujours-fatigue-malgre-le-sommeil", "penseur": "Pascal",
    "musique": "Ossuary-5---Rest.mp3", "noir": 3,
    "groupes": [
      "Huit heures / de sommeil.",
      "Et fatigué / au réveil.",
      "Ce n'est pas / le sommeil.",
      "Il y a quatre siècles, / Pascal écrivait",
      "que tout le malheur des hommes / vient d'une seule chose :",
      "ne pas savoir / rester en repos",
      "dans une *chambre*.",
      "Traduis-le / simplement.",
      "Ce qui fatigue, / ce n'est pas ce que tu fais.",
      "C'est ce que / tu +fuis+.",
      "L'écran qu'on rallume. / Le projet qu'on ajoute.",
      "Le silence / qu'on remplit.",
      "Fuir, / ça demande de l'énergie.",
      "Toute la journée.",
      "Alors essaie / une chose :",
      "dix minutes, / sans rien.",
      "Et note ce qui / !remonte!.",
      "C'est ça / qui te fatigue.",
    ] + CTA,
    "legende": "Huit heures de sommeil, et fatigué. Pascal : tout le malheur vient de ne pas savoir rester en repos dans une chambre.",
  },
  {
    "id": "17-telephone", "titre": 'Le téléphone en boucle', "images": ['scrolling phone bed', 'phone in hand close up', 'notification screen', 'people phones street', 'phone face down table', 'hand reaching phone'], "article": "verifier-son-telephone-en-boucle", "penseur": "Simone Weil",
    "musique": "Dark-Times.mp3", "noir": 3,
    "groupes": [
      "Tu l'as regardé / il y a une minute.",
      "Tu le regardes / !encore!.",
      "Rien / de nouveau.",
      "Il y a quatre-vingts ans, / une philosophe écrivait",
      "que l'attention / est la forme",
      "la plus rare / et la plus pure / de la *générosité*.",
      "Elle s'appelait / Simone Weil.",
      "Traduis-le / simplement.",
      "Ton attention / est ce que tu as / de plus précieux.",
      "Et tu la donnes / à un écran",
      "qui n'a / +rien+ à te dire.",
      "Ce n'est pas / une habitude.",
      "C'est une émotion / qui cherche une sortie.",
      "L'ennui. / L'attente. / Un peu de peur.",
      "Alors la prochaine fois / que ta main part,",
      "arrête-la / une seconde.",
      "Et demande : / qu'est-ce que je ne veux pas / ressentir, là ?",
      "La réponse vient / vite.",
    ] + CTA,
    "legende": "Tu l'as regardé il y a une minute. Simone Weil : l'attention est la forme la plus rare de la générosité — et tu la donnes à un écran.",
  },
  {
    "id": "18-parents", "titre": 'Voir ses parents vieillir', "images": ['elderly hands', 'old parents walking', 'aging mother daughter', 'wrinkled hands holding', 'family dinner table', 'old photo album'], "article": "voir-ses-parents-vieillir", "penseur": "Montaigne",
    "musique": "Long-Note-One.mp3", "noir": 3,
    "groupes": [
      "Un geste / plus lent.",
      "Une phrase / répétée deux fois.",
      "Et quelque chose / se serre.",
      "Il y a quatre siècles, / Montaigne écrivait",
      "que la plus grande chose / du monde",
      "est de savoir / *être à soi*.",
      "Et il l'a écrit / en regardant / son propre âge.",
      "Traduis-le / simplement.",
      "Ce qui se serre / quand tu les vois vieillir",
      "n'est pas / de la pitié.",
      "C'est de l'+amour+ / qui découvre / qu'il a une durée.",
      "Et ça, / on ne le règle pas.",
      "On le / regarde.",
      "Alors fais / une chose simple :",
      "la prochaine fois, / pose une question",
      "que tu n'as jamais / posée.",
      "Sur eux. / Sur avant toi.",
      "Ce serrement / cherche du temps.",
      "Donne-lui / !celui-là!.",
    ] + CTA,
    "legende": "Un geste plus lent, une phrase répétée. Ce qui se serre n'est pas de la pitié — c'est de l'amour qui découvre qu'il a une durée.",
  },
  {
    "id": "19-gratitude", "titre": 'La gratitude', "images": ['thank you note', 'helping hand', 'friends hugging', 'coffee offered', 'written letter', 'sunrise gratitude'], "article": "gratitude", "penseur": "Cicéron",
    "musique": "Dreams-Become-Real.mp3", "noir": 3,
    "groupes": [
      "Quelqu'un t'a aidé / cette semaine.",
      "Tu as dit / *merci*.",
      "Et tu es passé / à autre chose.",
      "Il y a deux mille ans, / Cicéron plaidait / devant un tribunal",
      "et il a dit / cette phrase :",
      "la gratitude n'est pas seulement / la plus grande des vertus,",
      "elle est la +mère+ / de toutes les autres.",
      "Traduis-le / simplement.",
      "Le merci que tu as dit / a duré une seconde.",
      "La gratitude, / c'est ce qui reste",
      "quand tu y repenses / le soir.",
      "Et la plupart des gens / n'y repensent !jamais!.",
      "Alors fais / l'essai :",
      "ce soir, / une chose",
      "que quelqu'un a faite / pour toi / aujourd'hui.",
      "Une seule.",
      "Tu vas voir / que c'est difficile.",
      "Pas parce qu'il n'y en a pas.",
      "Parce que tu ne les / *comptes* pas.",
    ] + CTA,
    "legende": "Tu as dit merci et tu es passé à autre chose. Cicéron appelait la gratitude la mère de toutes les vertus.",
  },
  {
    "id": "20-ne-plus-rien-ressentir", "titre": 'Ne plus rien ressentir', "images": ['blank stare', 'grey empty room', 'foggy morning', 'person still window', 'muted colors landscape', 'numb'], "article": "ne-plus-rien-ressentir", "penseur": "Spinoza",
    "musique": "Shadowlands-1---Horizon.mp3", "noir": 3,
    "groupes": [
      "Rien ne te touche / vraiment.",
      "Ni en bien. / Ni en mal.",
      "Et tu appelles ça / *le calme*.",
      "Il y a trois siècles et demi, / Spinoza écrivait",
      "que la joie est le passage / à une perfection +plus grande+,",
      "et la tristesse, / le passage / à une plus !petite!.",
      "Des passages. / Des mouvements.",
      "Traduis-le / simplement.",
      "Sentir, / c'est bouger.",
      "Ne plus rien sentir, / ce n'est pas la paix.",
      "C'est / l'arrêt.",
      "Et l'arrêt a souvent / une raison :",
      "quelque chose / a fait trop mal,",
      "et tout a été / baissé d'un coup.",
      "Alors cherche / la dernière fois",
      "où tu as senti / quelque chose de *fort*.",
      "Et regarde ce qui / s'est passé / juste après.",
      "C'est là / que ça s'est éteint.",
    ] + CTA,
    "legende": "Rien ne te touche, et tu appelles ça le calme. Spinoza : la joie et la tristesse sont des mouvements. L'absence, c'est l'arrêt.",
  },
]

assert len(SCRIPTS) == 20, len(SCRIPTS)
assert len({s["id"] for s in SCRIPTS}) == 20
