# -*- coding: utf-8 -*-
"""Les vingt scripts des vidéos. Un script = une liste de groupes de mots.

Chaque groupe est ce qui s'affiche à l'écran en même temps. Il n'y a pas de
voix : la lecture fait le rythme, et chaque groupe reste à l'écran le temps
qu'il faut pour le lire. On écrit donc des phrases entières, douces, explicites —
pas des fragments.

Trois marques, à l'intérieur d'un groupe :
    *mot*    le mot ressort en jaune
    !mot!    en rouge
    +mot+    en vert
    /        ce qui précède est la ligne large, ce qui suit la ligne étroite

« noir » : combien de groupes, au début, passent sur fond noir avant la première
image — c'est l'accroche.

« images » : ce que les fonds doivent montrer, en anglais pour la banque d'images.
Jamais d'humain : des paysages, des orages, de la lumière, de la matière.
« fantastique » : cinq vidéos en images imaginaires plutôt que réelles.

Chaque script part d'un article du guide (« article »), qui est la matière du
texte et le lien de la légende. Le penseur cité l'est pour une idée qu'il a
réellement écrite, paraphrasée — jamais une citation inventée.

Ce que les scripts ne disent JAMAIS : que le test est gratuit (il ne l'est pas),
un prix, ou quoi que ce soit qui ressemble à un diagnostic.
"""

CTA = [
    "Seize situations du quotidien, / quatorze émotions,",
    "et la place / qu'elles occupent chez toi.",
    "Fais le test. / Le lien est en *bio*.",
]

SCRIPTS = [
  {
    "id": "01-ca-va", "titre": "Répondre que ça va", "article": "repondre-que-ca-va", "penseur": "Darwin",
    "musique": "Dark-Times.mp3", "noir": 3, "fantastique": False,
    "images": ["calm lake surface morning", "still water hiding depth", "storm behind calm sky", "closed wooden shutters", "grey sea horizon", "fog over quiet field"],
    "groupes": [
      "Tu réponds *ça va* / dix fois par jour.",
      "Et tu sais très bien / que ce n'est pas tout à fait vrai.",
      "Ton visage, lui, / ne sait pas mentir.",
      "Il y a cent cinquante ans, Darwin observait / que l'émotion s'écrit sur le visage",
      "+avant même+ / qu'on décide de la montrer.",
      "Les sourcils, la mâchoire, le souffle : / ils parlent une seconde avant toi.",
      "Autrement dit, ce que tu ne dis pas / se voit quand même.",
      "Alors, cette semaine, / compte doucement",
      "combien de fois tu as répondu *ça va* / alors que ce n'était pas le cas.",
      "Si c'est plus de trois, / ce n'est pas de la politesse.",
      "C'est une émotion / qui n'a pas encore trouvé son mot.",
      "Et une émotion sans mot ne disparaît pas : / elle *attend* qu'on la nomme.",
    ] + CTA,
    "legende": "Tu dis « ça va » et ton visage dit autre chose. Darwin l'avait vu avant tout le monde.",
  },
  {
    "id": "02-colere", "titre": "La colère", "article": "colere", "penseur": "Sénèque",
    "musique": "Anguish.mp3", "noir": 3, "fantastique": False,
    "images": ["lightning storm dark sky", "volcano eruption lava", "crashing waves rocks", "wildfire night", "dark storm clouds rolling", "thunderstorm over field"],
    "groupes": [
      "Tu as claqué / une porte.",
      "Et une heure plus tard, / tu ne sais plus très bien !pourquoi!.",
      "Ce n'est pas grave. / Et ce n'est pas nouveau.",
      "Il y a deux mille ans, Sénèque écrivait / que la colère est une *courte folie*.",
      "Pas une faiblesse, pas un défaut : / une tempête qui passe.",
      "Et qu'on peut apprendre / à voir venir.",
      "Parce que la colère envoie toujours / un +signal+ avant d'éclater.",
      "La mâchoire qui se serre. / Le ton qui monte d'un cran.",
      "La phrase qu'on prépare / au lieu d'écouter.",
      "Ce signal, / tu l'as déjà.",
      "La seule question, / c'est de le voir *avant* la porte.",
      "Ce n'est pas une affaire de caractère. / C'est une affaire d'entraînement.",
    ] + CTA,
    "legende": "La colère est une courte folie, écrivait Sénèque. Elle envoie un signal, et il arrive avant la porte qui claque.",
  },
  {
    "id": "03-ruminer", "titre": "Ruminer une critique", "article": "ruminer-une-critique-au-travail", "penseur": "Marc Aurèle",
    "musique": "Long-Note-Two.mp3", "noir": 3, "fantastique": True,
    "images": ["labyrinth maze aerial fantasy", "spiral staircase infinite", "surreal endless corridor", "echo cave dark fantasy", "swirling vortex clouds", "hall of mirrors surreal"],
    "groupes": [
      "Une phrase, / en réunion.",
      "Cinq secondes / pour la dire.",
      "!Trois jours! / pour y repenser.",
      "Il y a dix-huit siècles, un empereur / écrivait, pour lui seul :",
      "si une chose extérieure te fait souffrir, / ce n'est pas elle qui te trouble,",
      "c'est le *jugement* / que tu portes sur elle.",
      "Il s'appelait / Marc Aurèle.",
      "Autrement dit : la critique a duré cinq secondes. / Le reste, c'est toi qui l'ajoutes.",
      "Alors essaie une chose simple : / sépare ce qui a été +dit+",
      "de ce que tu as / *entendu*.",
      "Écris les deux. / Souvent, ce n'est pas la même phrase.",
      "Et c'est la deuxième / qui te tient éveillé.",
    ] + CTA,
    "legende": "Cinq secondes pour la dire, trois jours pour la ruminer. Marc Aurèle avait un mot pour ça.",
  },
  {
    "id": "04-dimanche-soir", "titre": "Le dimanche soir", "article": "angoisse-dimanche-soir", "penseur": "Alain",
    "musique": "Colorless-Aura.mp3", "noir": 3, "fantastique": False,
    "images": ["dusk city lights empty street", "rain on window evening", "grey sky sunday evening", "street lamp fog night", "empty road at dusk", "apartment windows lit night"],
    "groupes": [
      "Dimanche, / dix-huit heures.",
      "Rien ne s'est passé. / Et pourtant, quelque chose !descend!.",
      "Tu connais / cette heure-là.",
      "Il y a un siècle, un professeur de lycée / écrivait chaque jour un court texte sur le bonheur.",
      "Il s'appelait Alain, / et il disait ceci :",
      "le pessimisme est d'*humeur*, / l'optimisme est de +volonté+.",
      "Autrement dit, ce qui descend le dimanche soir / n'est pas une idée.",
      "C'est une humeur. / Elle vient toute seule.",
      "Ce qui ne vient pas tout seul, / c'est ce que tu en fais.",
      "Alors, dimanche prochain, / regarde bien :",
      "est-ce que tu redoutes toute la semaine, / ou *une seule chose*",
      "que tu n'as pas / encore nommée ?",
      "Ce n'est jamais / toute la semaine.",
    ] + CTA,
    "legende": "Dimanche, 18 h, et quelque chose descend. Ce n'est jamais toute la semaine — c'est une chose, pas encore nommée.",
  },
  {
    "id": "05-jalousie-couple", "titre": "La jalousie dans le couple", "article": "jalousie-dans-le-couple", "penseur": "La Rochefoucauld",
    "musique": "Cold-Sober.mp3", "noir": 3, "fantastique": False,
    "images": ["tangled roots forest", "thorns branches close up", "dark water ripples", "fog between two trees", "mist over lake dawn", "cracked dry earth"],
    "groupes": [
      "Un prénom, / dans une conversation.",
      "Et tout à coup, / tu te mets à +surveiller+.",
      "Tu détestes ça. / Tu le fais quand même.",
      "Il y a quatre siècles, un moraliste français / écrivait que la jalousie",
      "se nourrit / dans les *doutes*,",
      "et qu'elle s'éteint / dès qu'on passe du doute à la certitude.",
      "Il s'appelait / La Rochefoucauld.",
      "Autrement dit, la jalousie ne vit pas / de ce que tu sais.",
      "Elle vit de ce que / tu ne sais !pas!.",
      "Alors pose-toi la vraie question : / de quoi as-tu peur ?",
      "Pas de qui. / De *quoi*.",
      "D'être remplacé ? De ne pas suffire ? / De l'avoir déjà senti, une fois ?",
      "Ce n'est pas l'autre / qui te répondra.",
      "C'est toi.",
    ] + CTA,
    "legende": "La jalousie se nourrit dans les doutes, écrivait La Rochefoucauld. La question n'est pas « qui ». C'est « de quoi ».",
  },
  {
    "id": "06-message-vu", "titre": "Message vu, sans réponse", "article": "message-vu-sans-reponse", "penseur": "Sénèque",
    "musique": "Heart-of-Nowhere.mp3", "noir": 3, "fantastique": False,
    "images": ["empty bench fog park", "still lake waiting dawn", "hourglass sand close up", "empty road horizon", "silent snow field", "clock tower night"],
    "groupes": [
      "*Vu*. / Il y a deux heures.",
      "Et toujours / rien.",
      "Ta tête a déjà écrit / trois histoires différentes.",
      "Il y a deux mille ans, Sénèque écrivait à un ami / que nous souffrons plus souvent",
      "en *imagination* / qu'en +réalité+.",
      "Autrement dit, le message n'a rien dit. / Le silence non plus.",
      "Les trois histoires, / c'est toi qui les as écrites.",
      "Alors fais l'expérience : / écris ce que tu crois que ce silence veut dire.",
      "Puis écris / ce que tu !sais! vraiment.",
      "Compare les deux colonnes. / La première est pleine, la seconde est vide.",
      "Ce n'est pas un signe. / C'est une attente.",
      "Et une attente, / ça se regarde sans lui inventer une histoire.",
    ] + CTA,
    "legende": "« Vu », il y a deux heures. Sénèque l'écrivait déjà : on souffre plus souvent en imagination qu'en réalité.",
  },
  {
    "id": "07-parler-en-reunion", "titre": "Parler en réunion", "article": "peur-de-parler-en-reunion", "penseur": "Montaigne",
    "musique": "Shadowlands-1---Horizon.mp3", "noir": 3, "fantastique": False,
    "images": ['cliff edge over sea fog', 'open sky wide field wind', 'mountain summit above clouds', 'bridge into fog', 'first light over valley', 'pier into mist lake'],
    "groupes": [
      "Tu avais / la bonne idée.",
      "Tu l'as gardée / pour toi.",
      "Quelqu'un l'a dite / dix minutes plus tard.",
      "Il y a quatre siècles, Montaigne écrivait / que ce dont il avait le plus peur,",
      "c'était / la *peur* elle-même.",
      "Pas la chose. / La peur de la chose.",
      "Autrement dit, ce n'est pas la réunion / qui te bloque.",
      "C'est ce que tu imagines / +avant+ : le silence après ta phrase, un regard.",
      "Et aucun des deux / n'est arrivé.",
      "Alors, la prochaine fois, observe : / ta gorge se serre-t-elle quand tu parles,",
      "ou !avant! / de parler ?",
      "Si c'est avant, ce n'est pas un manque de courage. / C'est une peur qui a pris de l'avance.",
    ] + CTA,
    "legende": "Ce dont j'ai le plus peur, c'est la peur, écrivait Montaigne. En réunion, elle arrive avant la phrase.",
  },
  {
    "id": "08-surprise", "titre": "La surprise", "article": "surprise", "penseur": "Descartes",
    "musique": "Dreams-Become-Real.mp3", "noir": 3, "fantastique": True,
    "images": ["aurora borealis fantasy sky", "sudden light through clouds", "door opening to light fantasy", "shooting star night sky", "glowing portal forest", "lightning frozen moment surreal"],
    "groupes": [
      "Une seconde. / Pas plus.",
      "L'émotion la plus *courte* / de toutes.",
      "Et personne / n'y fait attention.",
      "Il y a quatre siècles, Descartes classait les passions, / et il en plaçait une avant toutes les autres.",
      "Pas la joie. / Pas la peur.",
      "L'*admiration* : / ce qu'on appelle aujourd'hui la surprise.",
      "Autrement dit, la surprise / est une porte.",
      "Ce qui entre après, / c'est la joie, la colère ou la peur.",
      "Mais la porte, / c'est elle.",
      "Alors observe, la prochaine fois / que quelque chose t'arrive :",
      "qu'est-ce qui suit / la seconde de surprise ?",
      "Toujours la même émotion, / ou une différente à chaque fois ?",
      "Ça en dit long / sur ce que tu !attends! du monde.",
    ] + CTA,
    "legende": "Descartes plaçait la surprise avant toutes les autres passions. C'est la porte — regarde ce qui entre après.",
  },
  {
    "id": "09-pleurer", "titre": "Pleurer pour un rien", "article": "pleurer-pour-un-rien", "penseur": "William James",
    "musique": "Ossuary-5---Rest.mp3", "noir": 3, "fantastique": False,
    "images": ["rain drops on window", "waterfall mist forest", "overflowing river after rain", "dew drops leaf macro", "rain on lake surface", "storm rain dark clouds"],
    "groupes": [
      "Une pub. Une chanson. / Un mot gentil.",
      "Et les larmes / montent.",
      "Pour *rien*, / dis-tu.",
      "Il y a cent quarante ans, un psychologue américain / a retourné la question.",
      "On croit qu'on pleure / parce qu'on est triste.",
      "William James disait : / on est triste parce qu'on +pleure+.",
      "Le corps / d'abord.",
      "Autrement dit, les larmes ne viennent pas / de la pub.",
      "Elles viennent d'un corps / qui était !plein!,",
      "et qui a trouvé / une sortie.",
      "Alors quand ça monte pour rien, / ne cherche pas ce qui vient d'arriver.",
      "Cherche ce qui s'accumule / depuis des jours.",
      "Le rien, / c'est seulement la goutte.",
    ] + CTA,
    "legende": "On ne pleure pas parce qu'on est triste — on est triste parce qu'on pleure, disait William James. Le corps d'abord.",
  },
  {
    "id": "10-trois-heures", "titre": "Trois heures du matin", "article": "se-reveiller-a-3h-du-matin", "penseur": "Kierkegaard",
    "musique": "Long-Note-One.mp3", "noir": 3, "fantastique": True,
    "images": ["moon over dark sea fantasy", "starry night sky dreamlike", "floating island night surreal", "milky way over mountains", "dark forest moonlight fantasy", "night sky clouds surreal glow"],
    "groupes": [
      "Trois heures / du matin.",
      "Les yeux ouverts, / et une pensée qui !tourne!.",
      "La même / que la nuit dernière.",
      "Il y a deux siècles, un philosophe danois / appelait l'angoisse",
      "le *vertige* / de la liberté.",
      "Il s'appelait / Kierkegaard.",
      "Autrement dit : à trois heures du matin, / tu n'as rien à faire.",
      "Aucune tâche, aucun rendez-vous, / rien pour tenir la pensée.",
      "Alors elle regarde le vide, / et le vide lui donne le vertige.",
      "Ce n'est pas le problème / qui te réveille.",
      "C'est l'+espace+ / qu'il trouve à cette heure-là.",
      "Alors note-le, vraiment, / sur un papier.",
      "Pas pour le résoudre. / Pour lui donner un endroit où être",
      "qui ne soit pas / ta tête.",
    ] + CTA,
    "legende": "Trois heures du matin, et la même pensée. Kierkegaard appelait ça le vertige de la liberté.",
  },
  {
    "id": "11-imposteur", "titre": "Le syndrome de l'imposteur", "article": "syndrome-imposteur", "penseur": "Épictète",
    "musique": "Echoes-of-Time-v2.mp3", "noir": 3, "fantastique": False,
    "images": ["mirror lake reflection mountains", "empty theater stage spotlight", "venetian mask on table", "empty podium spotlight", "reflection in still water", "spotlight fog stage"],
    "groupes": [
      "On te félicite.",
      "Et une voix, à l'intérieur, dit : / *ils vont finir par voir*.",
      "Voir que tu ne mérites pas / d'être là.",
      "Il y a deux mille ans, un ancien esclave devenu philosophe / n'enseignait qu'une seule chose :",
      "distinguer ce qui +dépend+ de toi / de ce qui !n'en dépend pas!.",
      "Il s'appelait / Épictète.",
      "Autrement dit : ton travail / dépend de toi.",
      "Leur verdict / ne dépend pas de toi.",
      "Et la voix qui dit *ils vont voir* / passe sa vie dans la deuxième colonne.",
      "Alors fais l'inventaire : / ce que tu as fait, vraiment, cette semaine.",
      "Pas ce qu'ils en penseront. / Ce que tu as fait.",
      "La liste est plus longue / que la voix.",
      "Elle l'est / toujours.",
    ] + CTA,
    "legende": "« Ils vont voir. » Épictète répondait déjà : sépare ce qui dépend de toi de ce qui n'en dépend pas.",
  },
  {
    "id": "12-dire-non", "titre": "Dire non", "article": "culpabilite-de-dire-non", "penseur": "Aristote",
    "musique": "Lost-Frontier.mp3", "noir": 3, "fantastique": False,
    "images": ["closed gate in field", "old wooden door stone wall", "fence line countryside", "boundary stone wall hills", "garden gate morning light", "path with closed barrier"],
    "groupes": [
      "Tu as dit *oui*.",
      "Tu voulais / dire non.",
      "Et maintenant, / tu t'en veux d'avoir dit oui.",
      "Il y a deux mille quatre cents ans, Aristote écrivait / qu'une émotion est juste",
      "quand elle vise la bonne personne, / au bon +moment+, pour la bonne raison.",
      "Autrement dit, dire non / n'est pas une faute.",
      "C'est une émotion / qui a trouvé sa bonne adresse.",
      "Ce qui te fait mal, / ce n'est pas le non.",
      "C'est l'idée que l'autre / va !moins t'aimer!.",
      "Alors vérifie : la dernière fois / que quelqu'un t'a dit non,",
      "est-ce que tu l'as aimé moins ? / Ou tu as juste réorganisé ta journée ?",
      "C'est exactement / ce qu'il fera aussi.",
    ] + CTA,
    "legende": "Tu as dit oui, tu voulais dire non. Aristote : une émotion est juste quand elle vise la bonne personne, au bon moment.",
  },
  {
    "id": "13-amitie", "titre": "L'amitié qui s'éloigne", "article": "amitie-qui-seloigne", "penseur": "Aristote",
    "musique": "Colorless-Aura.mp3", "noir": 3, "fantastique": False,
    "images": ["two trees apart field", "diverging roads countryside", "footprints on sand beach", "two empty chairs by lake", "parallel paths forest", "distant lights across water"],
    "groupes": [
      "Vous étiez / inséparables.",
      "Et maintenant, / un message tous les trois mois.",
      "Personne n'a rien fait. / Ça s'est juste !éloigné!.",
      "Il y a deux mille quatre cents ans, / Aristote distinguait trois amitiés :",
      "celle de l'*utilité*, / celle du *plaisir*,",
      "et celle de ce qu'on est, / au fond.",
      "Les deux premières finissent / quand leur raison finit.",
      "La troisième, / non.",
      "Autrement dit, si l'amitié s'éloigne / quand le contexte change,",
      "c'était l'amitié du contexte. / Ce n'est pas une trahison : c'est sa nature.",
      "Alors demande-toi ce qui te manque : / la +personne+,",
      "ou l'époque / où vous étiez ensemble ?",
      "La réponse change / ce que tu dois faire.",
    ] + CTA,
    "legende": "Inséparables, puis un message tous les trois mois. Aristote distinguait trois amitiés — et une seule survit au changement.",
  },
  {
    "id": "14-rupture", "titre": "Après la rupture", "article": "apres-la-rupture", "penseur": "Stendhal",
    "musique": "Anguish.mp3", "noir": 3, "fantastique": True,
    "images": ["crystal cave glowing fantasy", "frozen tree ice crystals", "salt crystals macro glitter", "frozen branch sparkling frost", "crystal formation blue light", "ice cave surreal light"],
    "groupes": [
      "C'est fini / depuis deux mois.",
      "Et tu penses encore à cette personne / comme si elle était *parfaite*.",
      "Il y a deux siècles, Stendhal a décrit / ce que fait l'amour à ce qu'on regarde :",
      "il le couvre / de +cristaux+.",
      "Une branche jetée dans une mine de sel / en ressort couverte de diamants.",
      "Il appelait ça / la cristallisation.",
      "Autrement dit, la personne qui te manque / n'existe pas tout à fait.",
      "Elle est couverte de cristaux, / et c'est toi qui les as posés.",
      "Alors fais l'exercice : / écris trois choses qui t'agaçaient, vraiment.",
      "Si tu n'en trouves / !aucune!,",
      "ce n'est pas que c'était parfait. / C'est que tu regardes encore la branche.",
    ] + CTA,
    "legende": "Deux mois après, cette personne te semble parfaite. Stendhal avait un mot pour ça : la cristallisation.",
  },
  {
    "id": "15-reconnaissance", "titre": "Le manque de reconnaissance", "article": "manque-de-reconnaissance-travail", "penseur": "Épicure",
    "musique": "Cold-Sober.mp3", "noir": 3, "fantastique": False,
    "images": ["single flower growing stone", "lighthouse night sea", "small candle dark room", "hidden path forest light", "lone tree hill sunrise", "wildflower in crack rock"],
    "groupes": [
      "Tu as tenu / le projet.",
      "Quelqu'un d'autre / a reçu le *merci*.",
      "Et tu te dis / que ça ne te touche pas.",
      "Il y a deux mille trois cents ans, / Épicure séparait",
      "les désirs +naturels+ / des désirs !vains! :",
      "ceux qu'aucune quantité / ne remplit jamais.",
      "Autrement dit, le besoin d'être vu / est naturel.",
      "Mais le besoin que ce soit *lui* qui te voie, / à ce moment-là, devant tout le monde,",
      "c'est le désir / qui ne se remplit pas.",
      "Alors pose-toi la question : / qui, cette semaine, a vu ce que tu as fait ?",
      "Pas celui que tu attendais. / N'importe qui.",
      "Il y a presque toujours quelqu'un. / Et tu ne le comptes pas.",
    ] + CTA,
    "legende": "Tu as tenu le projet, un autre a eu le merci. Épicure séparait les désirs naturels de ceux qu'aucune quantité ne remplit.",
  },
  {
    "id": "16-fatigue", "titre": "Toujours fatigué", "article": "toujours-fatigue-malgre-le-sommeil", "penseur": "Pascal",
    "musique": "Ossuary-5---Rest.mp3", "noir": 3, "fantastique": False,
    "images": ["long empty road desert", "foggy morning heavy sky", "sand dunes endless", "grey overcast sea", "misty road forest", "still empty room window light"],
    "groupes": [
      "Huit heures / de sommeil.",
      "Et fatigué / au réveil.",
      "Ce n'est pas / le sommeil.",
      "Il y a quatre siècles, Pascal écrivait / que tout le malheur des hommes",
      "vient de ne pas savoir / rester en repos dans une *chambre*.",
      "Autrement dit, ce qui fatigue / n'est pas ce que tu fais.",
      "C'est ce que / tu +fuis+.",
      "L'écran qu'on rallume. / Le projet qu'on ajoute. Le silence qu'on remplit.",
      "Fuir demande de l'énergie. / Toute la journée.",
      "Alors essaie une chose : / dix minutes, sans rien.",
      "Et note ce qui / !remonte!.",
      "C'est ça / qui te fatigue.",
    ] + CTA,
    "legende": "Huit heures de sommeil, et fatigué. Pascal : tout le malheur vient de ne pas savoir rester en repos dans une chambre.",
  },
  {
    "id": "17-telephone", "titre": "Le téléphone en boucle", "article": "verifier-son-telephone-en-boucle", "penseur": "Simone Weil",
    "musique": "Dark-Times.mp3", "noir": 3, "fantastique": False,
    "images": ['moth on lamp at night', 'neon glow dark alley', 'city lights blur night', 'lighthouse beam fog', 'glowing window in dark house', 'street lamp light rain night'],
    "groupes": [
      "Tu l'as regardé / il y a une minute.",
      "Tu le regardes / !encore!.",
      "Rien / de nouveau.",
      "Il y a quatre-vingts ans, une philosophe écrivait / que l'attention est la forme",
      "la plus rare et la plus pure / de la *générosité*.",
      "Elle s'appelait / Simone Weil.",
      "Autrement dit, ton attention est / ce que tu as de plus précieux.",
      "Et tu la donnes à un écran / qui n'a +rien+ à te dire.",
      "Ce n'est pas une habitude. / C'est une émotion qui cherche une sortie.",
      "L'ennui. L'attente. / Un peu de peur, parfois.",
      "Alors, la prochaine fois que ta main part, / arrête-la une seconde,",
      "et demande-toi : / qu'est-ce que je ne veux pas ressentir, là ?",
      "La réponse vient / vite.",
    ] + CTA,
    "legende": "Tu l'as regardé il y a une minute. Simone Weil : l'attention est la forme la plus rare de la générosité — et tu la donnes à un écran.",
  },
  {
    "id": "18-parents", "titre": "Voir ses parents vieillir", "article": "voir-ses-parents-vieillir", "penseur": "Montaigne",
    "musique": "Long-Note-One.mp3", "noir": 3, "fantastique": False,
    "images": ["old oak tree autumn", "autumn leaves falling golden", "weathered wood texture", "sunset over calm sea", "old stone house ivy", "seasons changing forest"],
    "groupes": [
      "Un geste / plus lent.",
      "Une phrase / répétée deux fois.",
      "Et quelque chose, en toi, / se serre.",
      "Il y a quatre siècles, Montaigne écrivait / que la plus grande chose du monde",
      "est de savoir / *être à soi*.",
      "Et il l'a écrit / en regardant son propre âge.",
      "Autrement dit, ce qui se serre / quand tu les vois vieillir",
      "n'est pas de la pitié. / C'est de l'+amour+ qui découvre qu'il a une durée.",
      "Et ça, on ne le règle pas. / On le regarde.",
      "Alors fais une chose simple : / la prochaine fois, pose une question",
      "que tu n'as jamais posée. / Sur eux. Sur avant toi.",
      "Ce serrement cherche du temps. / Donne-lui !celui-là!.",
    ] + CTA,
    "legende": "Un geste plus lent, une phrase répétée. Ce qui se serre n'est pas de la pitié — c'est de l'amour qui découvre qu'il a une durée.",
  },
  {
    "id": "19-gratitude", "titre": "La gratitude", "article": "gratitude", "penseur": "Cicéron",
    "musique": "Dreams-Become-Real.mp3", "noir": 3, "fantastique": False,
    "images": ["sunrise golden field", "sunlight through trees forest", "warm light meadow morning", "golden hour mountains", "rainbow after rain valley", "spring blossom light"],
    "groupes": [
      "Quelqu'un t'a aidé / cette semaine.",
      "Tu as dit *merci*, / et tu es passé à autre chose.",
      "Il y a deux mille ans, Cicéron plaidait devant un tribunal, / et il a dit cette phrase :",
      "la gratitude n'est pas seulement / la plus grande des vertus,",
      "elle est la +mère+ / de toutes les autres.",
      "Autrement dit, le merci que tu as dit / a duré une seconde.",
      "La gratitude, c'est ce qui reste / quand tu y repenses le soir.",
      "Et la plupart des gens / n'y repensent !jamais!.",
      "Alors fais l'essai, ce soir : / une chose que quelqu'un a faite pour toi aujourd'hui.",
      "Une seule.",
      "Tu vas voir / que c'est difficile.",
      "Pas parce qu'il n'y en a pas. / Parce que tu ne les *comptes* pas.",
    ] + CTA,
    "legende": "Tu as dit merci et tu es passé à autre chose. Cicéron appelait la gratitude la mère de toutes les vertus.",
  },
  {
    "id": "20-ne-plus-rien-ressentir", "titre": "Ne plus rien ressentir", "article": "ne-plus-rien-ressentir", "penseur": "Spinoza",
    "musique": "Shadowlands-1---Horizon.mp3", "noir": 3, "fantastique": True,
    "images": ["grey void fog surreal", "frozen still lake dreamlike", "empty desert monochrome surreal", "endless grey horizon fantasy", "dead tree in fog surreal", "muted landscape dreamscape"],
    "groupes": [
      "Rien ne te touche / vraiment.",
      "Ni en bien, / ni en mal.",
      "Et tu appelles ça / *le calme*.",
      "Il y a trois siècles et demi, Spinoza écrivait / que la joie est le passage",
      "à une perfection +plus grande+, / et la tristesse, à une plus !petite!.",
      "Des passages. / Des mouvements.",
      "Autrement dit, sentir, / c'est bouger.",
      "Ne plus rien sentir, / ce n'est pas la paix. C'est l'arrêt.",
      "Et l'arrêt a souvent une raison : / quelque chose a fait trop mal,",
      "et tout a été baissé / d'un coup.",
      "Alors cherche la dernière fois / où tu as senti quelque chose de *fort*,",
      "et regarde ce qui s'est passé / juste après.",
      "C'est là / que ça s'est éteint.",
    ] + CTA,
    "legende": "Rien ne te touche, et tu appelles ça le calme. Spinoza : la joie et la tristesse sont des mouvements. L'absence, c'est l'arrêt.",
  },
]

assert len(SCRIPTS) == 20, len(SCRIPTS)
assert len({s["id"] for s in SCRIPTS}) == 20
assert sum(1 for s in SCRIPTS if s["fantastique"]) == 5
